"""Add Short Solution model

Revision ID: 06738bca1152
Revises: 2935aa59ed25
Create Date: 2020-05-21 13:05:54.969620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06738bca1152'
down_revision = '2935aa59ed25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentQuizId', sa.Integer(), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('studentAnswer', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], name=op.f('fk_short_solution_questionId_question')),
    sa.ForeignKeyConstraint(['studentQuizId'], ['student_quiz.id'], name=op.f('fk_short_solution_studentQuizId_student_quiz')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_solution'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_solution')
    # ### end Alembic commands ###
