"""empty message

Revision ID: 22ebc0e42512
Revises: 59b6f7f9c7dc
Create Date: 2020-05-01 16:54:28.358144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ebc0e42512'
down_revision = '59b6f7f9c7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tutorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorId'], ['user.id'], name=op.f('fk_quiz_tutorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz'))
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))

    op.drop_table('quiz')
    # ### end Alembic commands ###
