"""empty message

Revision ID: 32e3fb840fcc
Revises: aafbf2c23d59
Create Date: 2020-04-30 14:02:45.182811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e3fb840fcc'
down_revision = 'aafbf2c23d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userType', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_user_type_user_type', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_userType_user_type'), 'user_type', ['userType'], ['id'])
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_userType_user_type'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_user_type_user_type', 'user_type', ['user_type'], ['id'])
        batch_op.drop_column('userType')

    # ### end Alembic commands ###
