"""add relationship request

Revision ID: 389b5768ee5b
Revises: 6485532b50ad
Create Date: 2020-05-06 20:50:18.348933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389b5768ee5b'
down_revision = '6485532b50ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.Column('request', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], name=op.f('fk_request_studentId_user')),
    sa.ForeignKeyConstraint(['tutorId'], ['user.id'], name=op.f('fk_request_tutorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
