"""add student quiz relationship model

Revision ID: 3c27dd2db97f
Revises: 389b5768ee5b
Create Date: 2020-05-11 16:38:05.077546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c27dd2db97f'
down_revision = '389b5768ee5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.id'], name=op.f('fk_student_quiz_quizId_quiz')),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], name=op.f('fk_student_quiz_studentId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_quiz'))
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('name')

    op.drop_table('student_quiz')
    # ### end Alembic commands ###
