"""empty message

Revision ID: 59b6f7f9c7dc
Revises: ebc4b8c1cdf1
Create Date: 2020-05-01 16:54:04.683828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b6f7f9c7dc'
down_revision = 'ebc4b8c1cdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_timestamp')

    op.drop_table('quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('userId', sa.INTEGER(), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_quiz')
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_timestamp', ['timestamp'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quizId', sa.INTEGER(), nullable=True),
    sa.Column('question', sa.VARCHAR(length=140), nullable=True),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_question')
    )
    # ### end Alembic commands ###
