"""empty message

Revision ID: 7701bc8a1cf4
Revises: 22ebc0e42512
Create Date: 2020-05-01 16:54:49.902674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7701bc8a1cf4'
down_revision = '22ebc0e42512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.id'], name=op.f('fk_question_quizId_quiz')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
