"""empty message

Revision ID: 865d6a4afc17
Revises: 32e3fb840fcc
Create Date: 2020-04-30 14:03:28.586299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865d6a4afc17'
down_revision = '32e3fb840fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_quiz_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_userId_user'), 'user', ['userId'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('passwordHash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('userName', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_userName'), ['userName'], unique=True)
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('firstname')
        batch_op.drop_column('username')
        batch_op.drop_column('lastname')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.drop_index(batch_op.f('ix_user_userName'))
        batch_op.drop_column('userName')
        batch_op.drop_column('passwordHash')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_quiz_userId_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
