"""empty message

Revision ID: 9b4c8b011371
Revises: 7701bc8a1cf4
Create Date: 2020-05-01 16:54:57.417421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4c8b011371'
down_revision = '7701bc8a1cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('possibleAnswer', sa.String(length=104), nullable=True),
    sa.Column('correctAnswer', sa.Boolean(name='ck_multi_answer_boolean'), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], name=op.f('fk_multi_answer_questionId_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multi_answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multi_answer')
    # ### end Alembic commands ###
