"""Update user table

Revision ID: 9ea04644ce96
Revises: f7d77e44e5b1
Create Date: 2020-04-30 11:07:22.770589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea04644ce96'
down_revision = 'f7d77e44e5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('user_type', 'user_type', ['user_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
