"""empty message

Revision ID: aafbf2c23d59
Revises: f990c9ec9226
Create Date: 2020-04-30 14:02:31.391509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafbf2c23d59'
down_revision = 'f990c9ec9226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_quiz_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_user_type_user_type'), 'user_type', ['user_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_user_type_user_type'), type_='foreignkey')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_quiz_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
