"""empty message

Revision ID: abeb48c0845a
Revises: 865d6a4afc17
Create Date: 2020-05-01 14:19:59.452071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abeb48c0845a'
down_revision = '865d6a4afc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], name=op.f('fk_job_studentId_user')),
    sa.ForeignKeyConstraint(['tutorId'], ['user.id'], name=op.f('fk_job_tutorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
