"""Add short answer table

Revision ID: c5fc85247993
Revises: 9b4c8b011371
Create Date: 2020-05-01 17:09:59.318039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fc85247993'
down_revision = '9b4c8b011371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correctAnswer', sa.String(length=140), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], name=op.f('fk_short_answer_questionId_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_short_answer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_answer')
    # ### end Alembic commands ###
