"""Rename models

Revision ID: de797f4b64b0
Revises: 9b4c8b011371
Create Date: 2020-05-01 17:40:02.528028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de797f4b64b0'
down_revision = '9b4c8b011371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutorId', sa.Integer(), nullable=True),
    sa.Column('studentId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], name=op.f('fk_user_relationship_studentId_user')),
    sa.ForeignKeyConstraint(['tutorId'], ['user.id'], name=op.f('fk_user_relationship_tutorId_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_relationship'))
    )
    op.create_table('multi_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('possibleAnswer', sa.String(length=104), nullable=True),
    sa.Column('correctAnswer', sa.Boolean(name='ck_multi_answer_boolean'), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], name=op.f('fk_multi_solution_questionId_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_multi_solution'))
    )
    op.drop_table('job')
    op.drop_table('multi_answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('questionId', sa.INTEGER(), nullable=True),
    sa.Column('possibleAnswer', sa.VARCHAR(length=104), nullable=True),
    sa.Column('correctAnswer', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('"correctAnswer" IN (0, 1)', name='ck_multi_answer_ck_multi_answer_boolean'),
    sa.ForeignKeyConstraint(['questionId'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_multi_answer')
    )
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tutorId', sa.INTEGER(), nullable=True),
    sa.Column('studentId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['studentId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tutorId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', name='pk_job')
    )
    op.drop_table('multi_solution')
    op.drop_table('user_relationship')
    # ### end Alembic commands ###
