"""add score table

Revision ID: e90c694c83f6
Revises: 3c27dd2db97f
Create Date: 2020-05-11 20:07:26.105787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90c694c83f6'
down_revision = '3c27dd2db97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentQuizId', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['studentQuizId'], ['student_quiz.id'], name=op.f('fk_score_studentQuizId_student_quiz')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
