"""Add question table

Revision ID: ebc4b8c1cdf1
Revises: abeb48c0845a
Create Date: 2020-05-01 16:31:00.115623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc4b8c1cdf1'
down_revision = 'abeb48c0845a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.id'], name=op.f('fk_question_quizId_quiz')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_quiz_userId_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_quiz_tutorId_user'), 'user', ['tutorId'], ['id'])
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_quiz_tutorId_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_quiz_userId_user', 'user', ['userId'], ['id'])
        batch_op.drop_column('tutorId')

    op.drop_table('question')
    # ### end Alembic commands ###
