"""Add UserType table

Revision ID: f7d77e44e5b1
Revises: ca45ca8ff789
Create Date: 2020-04-30 11:05:13.597907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d77e44e5b1'
down_revision = 'ca45ca8ff789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userType', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_type')
    # ### end Alembic commands ###
