"""empty message

Revision ID: f990c9ec9226
Revises: c9a798b0f3af
Create Date: 2020-04-30 14:00:41.082342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f990c9ec9226'
down_revision = 'c9a798b0f3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quiz_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userType', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_column('userType')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_timestamp'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
